services:

  postgres:
    image: postgres:17-alpine3.21
    container_name: postgres
    ports:
    - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # command: postgres -c 'max_connections=250'

  app:
    build:
      context: .
      dockerfile: dockerfile
    image: frejun_assignment
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - .:/home/apiuser/fastapi_app
    # command:
    #   - /bin/sh
    #   - -c
    #   - |
    #     alembic upgrade head
    depends_on:
      - postgres

volumes:
  pgdata:
    