services:

  postgres:
    image: postgres:17.6-alpine3.21
    container_name: postgres
    ports:
    - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=250'

  app:
    build:
      context: .
      dockerfile: dockerfile
    image: auth_service
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
    command:
      - /bin/bash
      - -c
      - |
        alembic upgrade head
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
    