"""ticket booking

Revision ID: 071bf73a2571
Revises: 
Create Date: 2025-09-22 07:27:33.174727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071bf73a2571'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trains',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_confirmed_berths', sa.Integer(), nullable=False),
    sa.Column('total_rac_berths', sa.Integer(), nullable=False),
    sa.Column('total_waiting_list', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_table('berths',
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('berth_number', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', name='berthtypeenum'), nullable=False),
    sa.Column('coach', sa.String(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_berths_id'), 'berths', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('pnr', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'RAC', 'WAITING_LIST', 'CANCELLED', name='ticketstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_pnr'), 'tickets', ['pnr'], unique=True)
    op.create_table('passengers',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('berth_id', sa.Integer(), nullable=True),
    sa.Column('needs_berth', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(age >= 5 AND needs_berth = TRUE) OR (age < 5 AND needs_berth = FALSE)', name='age_berth_constraint'),
    sa.ForeignKeyConstraint(['berth_id'], ['berths.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_id'), 'passengers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passengers_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_tickets_pnr'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_berths_id'), table_name='berths')
    op.drop_table('berths')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    # ### end Alembic commands ###
